/**
 * Prefab class skill 0 (F) for warrior / raider / mage / priest.
 * Tree ids where they exist (w_taunt, rd_overpower). Totems are class F
 * prefabs — ObjectStore trees have no totem node yet.
 */
export const CLASS_SKILL_0 = {
  warrior: {
    id: 'w_taunt',
    name: 'Taunt',
    kind: 'nova',
    classSkill: true,
    element: 'physical',
    color: 0xd8433a,
    mana: 0,
    stamina: 12,
    cd: 15,
    range: 8,
    damage: 0,
    heal: 0,
    telegraphSec: 0.28,
    taunt: true,
    defBonusSec: 8,
    defBonus: 0.4,
    anim: 'cast',
    slot: 0,
    key: 'F',
  },
  raider: {
    id: 'rd_overpower',
    name: 'Overpower',
    kind: 'slash',
    classSkill: true,
    element: 'physical',
    color: 0x8fd4ff,
    mana: 0,
    stamina: 14,
    cd: 8,
    range: 3.4,
    damage: 36,
    heal: 0,
    telegraphSec: 0.14,
    anim: 'attack',
    slot: 0,
    key: 'F',
  },
  mage: {
    id: 'm_spell_totem',
    name: 'Spell Totem',
    kind: 'nova',
    classSkill: true,
    element: 'arcane',
    color: 0xb070ff,
    mana: 18,
    stamina: 0,
    cd: 30,
    range: 2.4,
    damage: 0,
    heal: 0,
    telegraphSec: 0.4,
    anim: 'cast',
    slot: 0,
    key: 'F',
    totem: 'spell',
  },
  ranger: {
    id: 'r_invis',
    name: 'Invis',
    kind: 'nova',
    classSkill: true,
    element: 'shadow',
    color: 0x9b6cf0,
    mana: 12,
    stamina: 8,
    cd: 30,
    range: 2,
    damage: 0,
    heal: 0,
    telegraphSec: 0.2,
    anim: 'cast',
    slot: 0,
    key: 'F',
    invisSec: 8,
    shadowStrike: {
      id: 'r_shadow_strike',
      name: 'Shadow Strike',
      kind: 'slash',
      range: 8,
      damage: 44,
      stun: 3,
      anim: 'attack',
    },
    afterBuffSec: 5,
    dodgeBackBonusM: 1,
  },
  priest: {
    id: 'p_blessed_totem',
    name: 'Blessed Totem',
    kind: 'nova',
    classSkill: true,
    element: 'holy',
    color: 0xffe08a,
    mana: 18,
    stamina: 0,
    cd: 30,
    range: 2.4,
    damage: 0,
    heal: 0,
    telegraphSec: 0.4,
    anim: 'cast',
    slot: 0,
    key: 'F',
    totem: 'blessed',
  },
  thief: {
    id: 't_invis',
    name: 'Invis',
    kind: 'nova',
    classSkill: true,
    element: 'shadow',
    color: 0x9b6cf0,
    mana: 10,
    stamina: 8,
    cd: 30,
    range: 14,
    damage: 0,
    heal: 0,
    telegraphSec: 0.2,
    anim: 'cast',
    slot: 0,
    key: 'F',
    invisSec: 8,
    speedMul: 0.7,
    mark: {
      id: 't_marking_marks',
      name: 'Marking Marks',
      kind: 'projectile',
      maxStacks: 3,
      duration: 15,
      perStack: 0.02,
      anim: 'cast',
    },
    nextRangedStun: 2,
    nextMeleeSlow: 0.5,
    nextMeleeSec: 5,
    missChance: 0.5,
  },
  verduror: {
    id: 'v_iguana_form',
    name: 'Iguana Form',
    kind: 'nova',
    classSkill: true,
    element: 'nature',
    color: 0x6bbf4a,
    mana: 8,
    stamina: 6,
    cd: 8,
    range: 2,
    damage: 0,
    heal: 0,
    telegraphSec: 0.28,
    anim: 'cast',
    slot: 0,
    key: 'F',
    form: 'iguana',
  },
};

export function classSkill0(classId) {
  return CLASS_SKILL_0[classId] || null;
}
