/**
 * Last ~70 downloads (2026-08-20, D:\Games\Models) — dungeon use only.
 * Isolate mesh names. Do not load fused 50–800 MB showcases.
 */
export const DOWNLOAD_REVIEW = {
  use: [
    { file: 'modular_dungeon.glb', mb: 34.3, why: 'isolate Wall_Piece / Pillar / stones / barrel / chest — vertex-color kit', biomes: ['ancient', 'grim'], role: 'cover' },
    { file: 'rainforst_tample.glb', mb: 37, why: 'verdant shrine/entrance/boss vignette — not a replacement dungeon', biomes: ['verdant'], role: 'scene' },
    { file: 'ga_free_451_stylized_gothic_wall_torch.glb', mb: 30.3, why: 'wall torch replacement (compressed kit)', biomes: ['ancient', 'grim', 'molten', 'frost', 'verdant'], role: 'torch' },
    { file: '5_versions_of_stylized_smelter.glb', mb: 3.0, why: '5 joined smelter scenes for molten elite/boss/shrine', biomes: ['molten'], role: 'scene' },
    { file: 'low_poly_dungeon_pack (1).glb', mb: 2.3, why: 'pillars, full wall, door, chest, floor trap — interior LOS', biomes: ['ancient', 'grim'], role: 'cover' },
    { file: 'low_poly_simple_brick_modular_structures (1).glb', mb: 0.2, why: 'interior wall / door / pillar tiles ~2 m', biomes: ['ancient', 'molten', 'grim'], role: 'interior' },
    { file: 'halloween.glb', mb: 4.7, why: 'fence stages 0–3 as destroyable barriers; stones; coffins; walls', biomes: ['grim', 'verdant'], role: 'barrier' },
    { file: 'ice_spikes.glb', mb: 0.3, why: 'frost LOS spikes', biomes: ['frost'], role: 'cover' },
    { file: 'stone_pillars.glb', mb: 0.9, why: 'cover pillars', biomes: ['ancient', 'frost', 'grim'], role: 'cover' },
    { file: 'stone_pillars (1).glb', mb: 0.9, why: 'duplicate of stone_pillars — skip extra copy', biomes: ['ancient'], role: 'skip-dup' },
    { file: 'sacrificial_altar.glb', mb: 3.1, why: 'boss dais prop', biomes: ['grim', 'ancient'], role: 'dais' },
    { file: 'hand-painted_column.glb', mb: 2.5, why: 'column cover', biomes: ['ancient'], role: 'cover' },
    { file: 'stylized_rocks_-_stones.glb', mb: 7.8, why: 'debris isolate', biomes: ['molten', 'ancient'], role: 'debris' },
    { file: 'low_poly_hand_painted_stone_tomb.glb', mb: 4.0, why: 'tomb clutter', biomes: ['ancient', 'grim'], role: 'debris' },
    { file: 'rocky_stone_block.glb', mb: 20.9, why: 'block debris isolate (heavy — pick one mesh)', biomes: ['molten', 'ancient'], role: 'debris' },
    { file: 'simple_terrain_with_rock_debris.glb', mb: 18, why: 'debris isolate, not whole terrain', biomes: ['molten'], role: 'debris' },
    { file: 'lowpoly_torture_devices.glb', mb: 0.8, why: 'grim clutter', biomes: ['grim'], role: 'prop' },
    { file: 'stylized_basic_props (1).glb', mb: 8, why: 'crates/barrels isolate', biomes: ['ancient', 'grim'], role: 'debris' },
    { file: 'fantasy_rpg_assets_fifth_round.glb', mb: 0.6, why: 'small RPG props', biomes: ['ancient', 'verdant'], role: 'prop' },
    { file: 'assorted_plant_kit.glb', mb: 2.6, why: 'verdant clutter isolate', biomes: ['verdant'], role: 'prop' },
    { file: 'medieval_fantasy_contest_asset_-_lantern_posts.glb', mb: 0.1, why: 'torch/lantern posts', biomes: ['ancient', 'grim'], role: 'prop' },
    { file: 'village.glb', mb: 2.8, why: 'small town dressing isolate', biomes: ['verdant', 'grim'], role: 'dress' },
    { file: 'mine.glb', mb: 2.9, why: 'molten/ancient tunnel props isolate', biomes: ['molten', 'ancient'], role: 'dress' },
    { file: 'shrine_to_odin (1).glb', mb: 1.1, why: 'shrine stand-in', biomes: ['frost', 'ancient'], role: 'shrine' },
    { file: 'the_ancient.glb', mb: 2.4, why: 'ancient statue isolate', biomes: ['ancient'], role: 'prop' },
    { file: 'lokheim_arena_of_valor.glb', mb: 2.4, why: 'arena ring reference, not a map', biomes: ['grim'], role: 'ref' },
    { file: 'pvp_arena.glb', mb: 3.4, why: 'arena ring isolate', biomes: ['molten'], role: 'ref' },
    { file: 'dungeon (2).glb', mb: 6.9, why: 'dungeon shell isolate pieces', biomes: ['ancient'], role: 'ref' },
    { file: 'pillar4_obj.glb', mb: 4.7, why: 'single pillar cover', biomes: ['ancient', 'frost'], role: 'cover' },
    { file: 'stone_blocks___3daily_2017.glb', mb: 3.4, why: 'block debris', biomes: ['ancient', 'molten'], role: 'debris' },
    { file: 'archertower_modular_set (1).glb', mb: 10.8, why: 'tower modules isolate — not a map', biomes: ['ancient'], role: 'isolateLater' },
  ],
  isolateLater: [
    { file: 'medieval_plague_town_assets_pack.glb', mb: 58.7, why: 'grim town crates/carts — Maya polySurface names, never fuse' },
    { file: 'chinese_market (2).glb', mb: 13, why: 'fused FrontSide/BackSide stalls — isolate crates, not whole market' },
    { file: 'stylized_dungeon.glb', mb: 21.5, why: 'reference shell — do not replace Kenney carve' },
    { file: 'catacombs_map.glb', mb: 12.4, why: 'full map — isolate pieces only' },
    { file: 'entrance_to_fort (1).glb', mb: 34.4, why: 'mouth/door reference' },
    { file: 'bandits_camp_-_blockout.glb', mb: 28.9, why: 'camp clutter isolate' },
    { file: 'stylized_basic_props (1).glb', mb: 8, why: 'already in use if pieces extracted' },
    { file: 'environment_pack_-_egypt_props.glb', mb: 79.2, why: 'ancient dressing isolate' },
    { file: 'argh_-_props_environment_collection.glb', mb: 73.5, why: 'prop dump isolate' },
    { file: 'wooden_house.glb', mb: 52, why: 'too big — isolate beams/furniture' },
    { file: 'summer_cottage.glb', mb: 15.5, why: 'verdant cottage isolate' },
    { file: 'woodcutters_hut_stronghold_crusader_inspired.glb', mb: 22.1, why: 'hut isolate' },
    { file: 'escena_camp.glb', mb: 7.3, why: 'camp isolate' },
    { file: 'camp_light_xyz_daily.glb', mb: 17.7, why: 'camp lights isolate' },
    { file: 'enchanted_water_scene_with_candels.glb', mb: 31.5, why: 'candle props isolate' },
    { file: 'snow_terrain_low_poly.glb', mb: 31.8, why: 'frost ground isolate, not a map' },
  ],
  skip: [
    'angel_wings__wing_for_birds__wings.glb (132 MB)',
    'altar.glb (191 MB)',
    'gothic_candle_altar_wax_ritual_book.glb (127 MB)',
    'modular_interior_medieval_building_games_updated.glb (775 MB)',
    'golden_marble__tile_texture.glb (45 MB)',
    'concrete_floor_after_exploding__tile_texture.glb (88 MB)',
    'pbr_material_concrete_floor_2k.glb (15.9 MB — material dump)',
    'arena_side (1).glb (105 MB)',
    'lowpoly_steampunk_airship (1).glb',
    '5v5_game_map.glb',
    'chicken_gun_fruzer_coliseum',
    'minecraft_world_npc_village.glb',
    'toy_tower_map',
    'greenhouse',
    'gorilla_tag',
    'bomb_crack_ground_* (tile FX dumps)',
    'a_small_stylized_cart_with_a_weapon_shop.glb (67 MB fused)',
    'prison_breaker.glb',
    'ferus / peco_peco / army_general_turtle / lava_golem — character dumps, not dungeon kits',
    'uzumaki_naruto / uchiha_madara / ryu / levi_ackerman — not Warlords play bodies',
    'ore_hero / mutant_dragon / pied_piper / the_ancient fused heroes',
    'castle_wars_pavlov_vr.glb',
    'cloud_ring (1).glb',
    'pyramid (1).glb',
    'traders_tallship.glb',
    'wood.glb (material)',
  ],
};
