/**
 * Last ~70 downloads (2026-08-20, D:\Games\Models) — dungeon use only.
 * Isolate mesh names. Do not load fused 50–800 MB showcases.
 */
export const DOWNLOAD_REVIEW = {
  use: [
    { file: 'modular_dungeon.glb', mb: 34.3, why: 'isolate Wall_Piece / Pillar / stones / barrel / chest — vertex-color kit', biomes: ['ancient', 'grim'], role: 'cover' },
    { file: 'rainforst_tample.glb', mb: 37, why: 'verdant shrine/entrance/boss vignette — not a replacement dungeon', biomes: ['verdant'], role: 'scene' },
    { file: 'ga_free_451_stylized_gothic_wall_torch.glb', mb: 30.3, why: 'wall torch replacement (compressed kit)', biomes: ['ancient', 'grim', 'molten', 'frost', 'verdant'], role: 'torch' },
    { file: '5_versions_of_stylized_smelter.glb', mb: 3.0, why: '5 joined smelter scenes for molten elite/boss/shrine', biomes: ['molten'], role: 'scene' },
    { file: 'low_poly_dungeon_pack (1).glb', mb: 2.3, why: 'pillars, full wall, door, chest, floor trap — interior LOS', biomes: ['ancient', 'grim'], role: 'cover' },
    { file: 'low_poly_simple_brick_modular_structures (1).glb', mb: 0.2, why: 'interior wall / door / pillar tiles ~2 m', biomes: ['ancient', 'molten', 'grim'], role: 'interior' },
    { file: 'halloween.glb', mb: 4.7, why: 'fence stages 0–3 as destroyable barriers; stones; coffins; walls', biomes: ['grim', 'verdant'], role: 'barrier' },
    { file: 'ice_spikes.glb', mb: 0.3, why: 'frost LOS spikes', biomes: ['frost'], role: 'cover' },
    { file: 'stone_pillars.glb', mb: 0.9, why: 'cover pillars', biomes: ['ancient', 'frost', 'grim'], role: 'cover' },
    { file: 'stone_pillars (1).glb', mb: 0.9, why: 'duplicate of stone_pillars — skip extra copy', biomes: ['ancient'], role: 'skip-dup' },
    { file: 'sacrificial_altar.glb', mb: 3.1, why: 'boss dais prop', biomes: ['grim', 'ancient'], role: 'dais' },
    { file: 'hand-painted_column.glb', mb: 2.5, why: 'column cover', biomes: ['ancient'], role: 'cover' },
    { file: 'stylized_rocks_-_stones.glb', mb: 7.8, why: 'debris isolate', biomes: ['molten', 'ancient'], role: 'debris' },
    { file: 'low_poly_hand_painted_stone_tomb.glb', mb: 4.0, why: 'tomb clutter', biomes: ['ancient', 'grim'], role: 'debris' },
    { file: 'rocky_stone_block.glb', mb: 20.9, why: 'block debris isolate (heavy — pick one mesh)', biomes: ['molten', 'ancient'], role: 'debris' },
    { file: 'simple_terrain_with_rock_debris.glb', mb: 18, why: 'debris isolate, not whole terrain', biomes: ['molten'], role: 'debris' },
    { file: 'lowpoly_torture_devices.glb', mb: 0.8, why: 'grim clutter', biomes: ['grim'], role: 'prop' },
    { file: 'stylized_basic_props (1).glb', mb: 8, why: 'crates/barrels isolate', biomes: ['ancient', 'grim'], role: 'debris' },
    { file: 'fantasy_rpg_assets_fifth_round.glb', mb: 0.6, why: 'small RPG props', biomes: ['ancient', 'verdant'], role: 'prop' },
    { file: 'assorted_plant_kit.glb', mb: 2.6, why: 'verdant clutter isolate', biomes: ['verdant'], role: 'prop' },
    { file: 'medieval_fantasy_contest_asset_-_lantern_posts.glb', mb: 0.1, why: 'torch/lantern posts', biomes: ['ancient', 'grim'], role: 'prop' },
    { file: 'village.glb', mb: 2.8, why: 'small town dressing isolate', biomes: ['verdant', 'grim'], role: 'dress' },
    { file: 'mine.glb', mb: 2.9, why: 'molten/ancient tunnel props isolate', biomes: ['molten', 'ancient'], role: 'dress' },
    { file: 'shrine_to_odin (1).glb', mb: 1.1, why: 'shrine stand-in', biomes: ['frost', 'ancient'], role: 'shrine' },
    { file: 'the_ancient.glb', mb: 2.4, why: 'ancient statue isolate', biomes: ['ancient'], role: 'prop' },
    { file: 'lokheim_arena_of_valor.glb', mb: 2.4, why: 'arena ring reference, not a map', biomes: ['grim'], role: 'ref' },
    { file: 'pvp_arena.glb', mb: 3.4, why: 'arena ring isolate', biomes: ['molten'], role: 'ref' },
    { file: 'dungeon (2).glb', mb: 6.9, why: 'dungeon shell isolate pieces', biomes: ['ancient'], role: 'ref' },
    { file: 'pillar4_obj.glb', mb: 4.7, why: 'single pillar cover', biomes: ['ancient', 'frost'], role: 'cover' },
    { file: 'stone_blocks___3daily_2017.glb', mb: 3.4, why: 'block debris', biomes: ['ancient', 'molten'], role: 'debris' },
    { file: 'archertower_modular_set (1).glb', mb: 10.8, why: 'tower modules isolate — not a map', biomes: ['ancient'], role: 'isolateLater' },
    { file: 'valheim_workbench (2).glb', mb: 0.17, why: 'tiny craft station — shrine/treasure clutter', biomes: ['ancient', 'grim'], role: 'prop' },
    { file: 'weed_brick.glb', mb: 0.67, why: 'crate-sized block isolate, not plants', biomes: ['verdant'], role: 'debris' },
    { file: 'medieval_shack__hand_painted.glb', mb: 1.2, why: 'small shack isolate — entrance hut only', biomes: ['verdant', 'grim'], role: 'dress' },
    { file: 'rustic_wooden_hut.glb', mb: 3.9, why: 'hut isolate if <4 MB', biomes: ['verdant'], role: 'dress' },
  ],
  isolateLater: [
    { file: 'medieval_plague_town_assets_pack.glb', mb: 58.7, why: 'grim town crates/carts — Maya polySurface names, never fuse' },
    { file: 'chinese_market (2).glb', mb: 13, why: 'fused FrontSide/BackSide stalls — isolate crates, not whole market' },
    { file: 'stylized_dungeon.glb', mb: 21.5, why: 'reference shell — do not replace Kenney carve' },
    { file: 'catacombs_map.glb', mb: 12.4, why: 'full map — isolate pieces only' },
    { file: 'entrance_to_fort (1).glb', mb: 34.4, why: 'mouth/door reference' },
    { file: 'bandits_camp_-_blockout.glb', mb: 28.9, why: 'camp clutter isolate' },
    { file: 'stylized_basic_props (1).glb', mb: 8, why: 'already in use if pieces extracted' },
    { file: 'environment_pack_-_egypt_props.glb', mb: 79.2, why: 'ancient dressing isolate' },
    { file: 'argh_-_props_environment_collection.glb', mb: 73.5, why: 'prop dump isolate' },
    { file: 'wooden_house.glb', mb: 52, why: 'too big — isolate beams/furniture' },
    { file: 'summer_cottage.glb', mb: 15.5, why: 'verdant cottage isolate' },
    { file: 'woodcutters_hut_stronghold_crusader_inspired.glb', mb: 22.1, why: 'hut isolate' },
    { file: 'escena_camp.glb', mb: 7.3, why: 'camp isolate' },
    { file: 'camp_light_xyz_daily.glb', mb: 17.7, why: 'camp lights isolate' },
    { file: 'temple_ruins_asset_pack (1).glb', mb: 61, why: 'ruins pack — isolate columns/arches, never whole GLB' },
    { file: 'floating_town-hand_painted (1).glb', mb: 16, why: 'town isolate pieces only' },
    { file: 'wall.glb', mb: 26, why: 'single fused wall dump — skip unless one mesh <2 MB' },
    { file: 'japanese_paper_lanterns_collection.glb', mb: 26, why: 'lantern isolate for shrine, heavy atlas' },
    { file: 'enchanted_water_scene_with_candels.glb', mb: 31.5, why: 'candle props isolate' },
    { file: 'snow_terrain_low_poly.glb', mb: 31.8, why: 'frost ground isolate, not a map' },
  ],
  skip: [
    'angel_wings__wing_for_birds__wings.glb (132 MB)',
    'altar.glb (191 MB)',
    'gothic_candle_altar_wax_ritual_book.glb (127 MB)',
    'anime_stylized_room.glb (138 MB fused interior)',
    'medieval_houses_asset.glb (133 MB fused houses)',
    'kiz_ui_qazaq_ui_yurt.glb (80 MB yurt showcase)',
    'sponza_palace.glb (34 MB — Sponza is a lighting test, not a dungeon kit)',
    'orc_house (1).glb (32 MB fused RTS house)',
    'myth_total_war_model__* (units — not dungeon tiles; KayKit/Toon remain play bodies)',
    'training_camp.glb (69 MB fused)',
    'stylized_cedar_trees.glb (41 MB — instanced tree later, not now)',
    'flowering_cannabis_plant_in_a_pot.glb',
    'cannabis_plant_small_1.glb',
    'modular_interior_medieval_building_games_updated.glb (775 MB)',
    'golden_marble__tile_texture.glb (45 MB)',
    'concrete_floor_after_exploding__tile_texture.glb (88 MB)',
    'pbr_material_concrete_floor_2k.glb (15.9 MB — material dump)',
    'arena_side (1).glb (105 MB)',
    'lowpoly_steampunk_airship (1).glb',
    '5v5_game_map.glb',
    'chicken_gun_fruzer_coliseum',
    'minecraft_world_npc_village.glb',
    'toy_tower_map',
    'greenhouse',
    'gorilla_tag',
    'bomb_crack_ground_* (tile FX dumps)',
    'a_small_stylized_cart_with_a_weapon_shop.glb (67 MB fused)',
    'prison_breaker.glb',
    'ferus / peco_peco / army_general_turtle / lava_golem — character dumps, not dungeon kits',
    'uzumaki_naruto / uchiha_madara / ryu / levi_ackerman — not Warlords play bodies',
    'ore_hero / mutant_dragon / pied_piper / the_ancient fused heroes',
    'castle_wars_pavlov_vr.glb',
    'cloud_ring (1).glb',
    'pyramid (1).glb',
    'traders_tallship.glb',
    'wood.glb (material)',
  ],
};

/** Newest ~200 files in D:\Games\Models (2026-08-21). Peeked glTF JSON. Kenney carve stays generator. */
export const DOWNLOAD_REVIEW_0821 = {
  ready: [
    { file: 'crystal_bundle.glb', mb: 6.7, meshes: 11, why: '6 named crystal meshes — BREAKABLE / shrine / lava-shader skin', biomes: ['ancient', 'molten', 'frost'], role: 'breakable' },
    { file: 'magic_rocks.glb', mb: 4.3, meshes: 6, why: 'ISOLATED MagicRock_1–6 → models/vfx/rocks/magic-rock-N.glb (0.45 m). Never load fused pack. Staff/effect projectiles + shrine objects.', biomes: ['molten', 'ancient'], role: 'fissure' },
    { file: 'dungeon_floor_grate.glb', mb: 1.0, meshes: 4, why: 'floor grate tiles — SUBFLOOR / trap / LOS hole', biomes: ['ancient', 'grim'], role: 'floor' },
    { file: 'wolftrap.glb', mb: 0.2, meshes: 4, anims: ['Lock'], why: 'bear-trap with Lock clip — hidden trap on BREAKABLE/HIDDEN cells', biomes: ['grim', 'verdant'], role: 'trap' },
    { file: 'ballista (2).glb', mb: 0.2, meshes: 7, why: 'KayKit-scale turret — already wanted in kit; isolate wood/metal', biomes: ['ancient', 'grim'], role: 'turret' },
    { file: 'crates_and_barrels (4).glb', mb: 2.0, meshes: 234, why: 'crate/barrel variants — instanced debris; pick 4–8 unique, not 234', biomes: ['ancient', 'grim'], role: 'debris' },
    { file: 'stylized_rock (3).glb', mb: 1.9, meshes: 1, why: 'single SI rock — instanced debris', biomes: ['molten', 'ancient', 'frost'], role: 'debris' },
    { file: 'rocky_platform.glb', mb: 1.0, meshes: 1, why: 'dais / cover block ~1 mesh', biomes: ['ancient', 'molten'], role: 'dais' },
    { file: 'rock_stack.glb', mb: 0.05, meshes: 12, why: 'tiny stone stack — instanced clutter', biomes: ['ancient', 'frost'], role: 'debris' },
    { file: 'extraction_of_stones_ao.glb', mb: 0.4, meshes: 1, why: 'single AO stone', biomes: ['ancient'], role: 'debris' },
    { file: 'roots_and_vines.glb', mb: 0.1, meshes: 6, why: 'vine pieces — verdant walls / barriers', biomes: ['verdant'], role: 'barrier' },
    { file: 'intertwined_vines.glb', mb: 0.4, meshes: 7, why: 'vine+leaf isolate', biomes: ['verdant'], role: 'prop' },
    { file: 'fantasy_candle.glb', mb: 1.7, meshes: 1, why: 'candle — shrine clutter (pair with instanced fire, not a light per mesh)', biomes: ['ancient', 'grim'], role: 'prop' },
    { file: 'wood_burning_stove.glb', mb: 0.2, meshes: 21, why: 'tiny stove — shrine/camp clutter', biomes: ['grim', 'molten'], role: 'prop' },
    { file: 'metal_furnace_lowpoly.glb', mb: 0.9, meshes: 1, why: 'molten shrine furnace', biomes: ['molten'], role: 'scene' },
    { file: 'forge_handpainted.glb', mb: 4.1, meshes: 3, why: 'LOD0–2 forge — molten elite room (use Lod2)', biomes: ['molten'], role: 'scene' },
    { file: 'arrow_tower.glb', mb: 1.2, meshes: 2, why: 'bot+top tower — entrance / CustomGrudge lobby isolate', biomes: ['ancient'], role: 'entrance' },
    { file: 'free_lowpoly_medieval_fortress_asset_pack (1).glb', mb: 3.4, meshes: 31, why: 'named palisade/wall cubes — isolate 2.15 m tiles', biomes: ['ancient', 'grim'], role: 'interior' },
    { file: 'ancient_ruins_pack.glb', mb: 10.3, meshes: 33, why: 'Bricks/Pillar/Walls named — isolate, do not load whole 10 MB', biomes: ['ancient'], role: 'cover' },
    { file: 'local_warning_appear.glb', mb: 0.1, meshes: 7, anims: ['Take 001'], why: 'ring appear — telegraph / incoming (not a second tell engine)', biomes: ['all'], role: 'vfx' },
    { file: 'mushroom_grow_animation.glb', mb: 2.2, meshes: 1, anims: ['Take 001'], why: 'grow clip — verdant trap / shrine pop', biomes: ['verdant'], role: 'trap' },
    { file: 'wooden_golem (1).glb', mb: 0.1, meshes: 2, anims: ['Take 001'], why: 'tiny golem trash (~SI), one mixer — not play hero', biomes: ['verdant', 'ancient'], role: 'trash' },
    { file: 'rock_golem.glb', mb: 0.1, meshes: 2, anims: ['Take 001'], why: 'tiny rock golem trash', biomes: ['molten', 'ancient'], role: 'trash' },
    { file: 'papyrus.glb', mb: 0.7, meshes: 1, why: 'scroll clutter', biomes: ['ancient'], role: 'prop' },
    { file: 'papyrus.glb', mb: 0.7, meshes: 1, why: 'scroll clutter', biomes: ['ancient'], role: 'prop' },
    { file: 'stylized_tavern_sign.glb', mb: 0.8, meshes: 8, why: 'sign+chain — lobby/entrance', biomes: ['grim', 'verdant'], role: 'prop' },
  ],
  isolateLater: [
    { file: 'crates_and_barrels (4).glb', mb: 2.0, why: '234 meshes — pick unique crate/barrel only' },
    { file: 'magic_runestones (1).glb', mb: 29.3, why: 'named Stormfist/Firebolt/Icewave/Rune stones — isolate 3–4, skip 29 MB dump' },
    { file: 'gates_of_initiation.glb', mb: 6.1, why: '4 planes — entrance gate, check SI (may be giant)' },
    { file: 'dungeon (3).glb', mb: 16.5, why: 'Maya polySurface shell — isolate 1–2 pieces, not a map' },
    { file: 'sand_dungeon_pillar_1.glb', mb: 15.8, why: 'pillar+floor+rocks — isolate pillar only' },
    { file: 'gothic_architectural_structures.glb', mb: 17.2, why: 'GothCol 1–3 columns — isolate one column geo' },
    { file: 'elf_lord_temple.glb', mb: 1.1, why: 'statue/dais/plants — shrine isolate' },
    { file: 'potion_shop_old.glb', mb: 0.9, why: '438 tiny cubes — bottles isolate later, skip as scene' },
    { file: 'stylized_medieval_torch.glb', mb: 6.7, why: 'torch parts — isolate wood+metal; fire = instanced fire SSOT' },
    { file: 'cozy_campfire.glb', mb: 6.6, why: 'firewood morph — logs only; flame = instanced fire' },
    { file: 'stylized_fire_tornado (3).glb', mb: 1.1, why: '129 meshes + Scene clip — molten elite VFX isolate, not a second particle engine' },
    { file: 'explode_body_animated.glb', mb: 2.2, why: '120 polys + shatter clip — harvest pinata sibling to Crystal.FBX' },
    { file: 'animated_low_poly_explosion.glb', mb: 9.5, why: '53 cubes + Animation — fissure burst, Draco first' },
    { file: 'floor_smashedexploded (1).glb', mb: 20.9, why: '392 cells + Break clip — SUBFLOOR smash; too heavy to instance whole' },
    { file: 'crystal_bundle.glb', mb: 6.7, why: 'already in ready — Draco+isolate 6 crystals' },
    { file: 'orbs (1).glb / orb (2).glb', mb: '7–11', why: 'staff orbs — fleet orb SSOT already; isolate core only if better than fireball.glb extract' },
    { file: 'low_poly_environment.glb', mb: 3.7, why: 'rock/tree/water — verdant dress isolate, not a map' },
    { file: 'slum_modular.glb', mb: 1.9, why: 'House4/5 modules — grim lobby, not Kenney halls' },
    { file: 'voxel_fence_pack_01.glb', mb: 6.7, why: 'only 3 meshes — check if SI fence or fused voxel dump' },
    { file: 'chain.glb', mb: 6.5, why: 'torus chain — hanging clutter isolate' },
    { file: 'rpg_project_environment_lowpoly.glb', mb: 29.4, why: 'full env — isolate props only' },
  ],
  skip: [
    'stylized_modular_stonewalls.glb (260 MB)',
    'fivestory_building__appartament_of_post-soviet.glb (642 MB)',
    'old_church_ruins.glb (152 MB)',
    'katenturm_beta.glb (196 MB)',
    'Meshy_AI_Floating_Ruins_* (Meshy — not play, not Kenney)',
    'healer_/rogue_/high_knight_/lancer_/bow_trigger_ game_character (play body stays Toon {race}.glb)',
    'dark_warrior_game_character / mystical_watchtower character dumps',
    'kamehameha (1).glb (57 MB anime beam)',
    'abstract_geometry_fluid_seamless_loop (125 MB)',
    'material_library_showcase_only_free.glb',
    'phoenix_suns_promotional_collaboration.glb',
    'juggernaut_being_slammed_* (19 MB each)',
    'aztec_vending_machine, country_store, little_game_town, gangwar map',
    'cannabis_* / dank_nugz',
    'elven_treehouse_from_lord_of_the_rings (56 MB)',
    'orc_cabin (75 MB fused)',
    'health_pick_up sci-fi holo (wrong era chrome)',
    'survival_game_propasset_pack.glb (jerrycan/radio/compass — modern, not Warlords dungeon)',
    'grenade pack / cyber_isis / poly_pistol (wrong era unless Thief pistol isolate later)',
  ],
};
