/**
 * Authored dungeon creatures (local GLB, native clips + textures).
 * Hide author leftover Icosphere / extra heads. Fit visible body to SI height.
 */
export const CREATURES = {
  rock_monster: {
    id: 'rock_monster',
    label: 'Rock Brute',
    mesh: 'models/creatures/rock_monster.glb',
    clips: 'native',
    hide: /icosphere/i,
    height: 2.15,
    radius: 0.62,
    speed: 2.4,
    hp: 160,
    kind: 'elite',
    role: 'warrior',
    brain: 'pursue',
    biome: 'molten',
    biomes: ['molten', 'ancient'],
    attacks: ['slash', 'column', 'circle'],
    telegraph: 'aoe',
  },
  berserk: {
    id: 'berserk',
    label: 'Berserker',
    mesh: 'models/creatures/berserk.glb',
    clips: 'native',
    hide: /icosphere|tubby_head/i,
    height: 2.05,
    radius: 0.5,
    speed: 3.4,
    hp: 120,
    kind: 'elite',
    role: 'warrior',
    brain: 'pursue',
    biome: 'grim',
    biomes: ['grim', 'verdant'],
    attacks: ['slash', 'swipe', 'circle'],
    telegraph: 'cone',
  },
  troll: {
    id: 'troll',
    label: 'Cave Troll',
    mesh: 'models/creatures/troll.glb',
    clips: 'native',
    hide: /icosphere/i,
    keep: /troll|stick|eyes|teeth|body/i,
    height: 2.55,
    radius: 0.72,
    speed: 2.1,
    hp: 220,
    kind: 'miniboss',
    role: 'warrior',
    brain: 'pursue',
    biome: 'verdant',
    biomes: ['verdant', 'frost', 'ancient'],
    attacks: ['slash', 'column', 'circle', 'linear'],
    telegraph: 'aoe',
  },
  cave_dino: {
    id: 'cave_dino',
    label: 'Cave Dino',
    mesh: 'models/creatures/cave_dino.glb',
    clips: 'native',
    hide: /icosphere/i,
    height: 1.95,
    radius: 0.55,
    speed: 3.0,
    hp: 88,
    kind: 'caster',
    role: 'mage',
    brain: 'kite',
    biome: 'ancient',
    biomes: ['ancient', 'verdant'],
    attacks: ['linear', 'circle', 'slash'],
    telegraph: 'incoming',
  },
  rock_elemental: {
    id: 'rock_elemental', label: 'Rock Elemental', mesh: 'models/creatures/rock_elemental.glb',
    clips: 'native', hide: /icosphere/i, height: 2.25, radius: 0.7, speed: 2.0, hp: 180,
    kind: 'elite', role: 'warrior', brain: 'pursue', biome: 'molten',
    biomes: ['molten', 'ancient', 'frost'],
    attacks: ['earth_spike', 'column', 'slash'], telegraph: 'aoe',
  },
  desert_dragon: {
    id: 'desert_dragon', label: 'Desert Drake', mesh: 'models/creatures/desert_dragon.glb',
    clips: 'native', hide: /icosphere/i, height: 2.8, radius: 0.95, speed: 2.3, hp: 260,
    kind: 'miniboss', role: 'mage', brain: 'pursue', biome: 'ancient',
    biomes: ['ancient', 'molten'],
    attacks: ['fire_fan', 'slash', 'circle'], telegraph: 'incoming',
  },
  mutant_mantis: {
    id: 'mutant_mantis', label: 'Mutant Mantis', mesh: 'models/creatures/mutant_mantis.glb',
    clips: 'native', hide: /icosphere/i, height: 2.2, radius: 0.6, speed: 3.3, hp: 140,
    kind: 'elite', role: 'warrior', brain: 'pursue', biome: 'molten',
    biomes: ['molten', 'verdant'],
    attacks: ['slash', 'linear', 'column'], telegraph: 'cone',
  },
  shadow_flame_mantis: {
    id: 'shadow_flame_mantis', label: 'Shadow Flame Mantis', mesh: 'models/creatures/shadow_flame_mantis.glb',
    clips: 'native', hide: /icosphere/i, height: 2.35, radius: 0.68, speed: 3.1, hp: 210,
    kind: 'miniboss', role: 'mage', brain: 'pursue', biome: 'grim',
    biomes: ['grim', 'molten'],
    attacks: ['fire_fan', 'slash', 'mist'], telegraph: 'aoe',
  },
  forest_beetle: {
    id: 'forest_beetle', label: 'Forest Beetle', mesh: 'models/creatures/forest_beetle.glb',
    clips: 'native', hide: /icosphere/i, height: 1.7, radius: 0.7, speed: 2.4, hp: 95,
    kind: 'grunt', role: 'warrior', brain: 'pursue', biome: 'verdant',
    biomes: ['verdant', 'ancient'],
    attacks: ['slash', 'circle'], telegraph: 'cone',
  },
  spiderlit: {
    id: 'spiderlit', label: 'Lit Spider', mesh: 'models/creatures/spiderlit.glb',
    clips: 'native', hide: /icosphere/i, height: 1.35, radius: 0.55, speed: 3.6, hp: 70,
    kind: 'grunt', role: 'warrior', brain: 'pursue', biome: 'grim',
    biomes: ['grim', 'molten', 'ancient'],
    attacks: ['slash', 'swipe'], telegraph: 'cone',
  },
  spider: {
    id: 'spider', label: 'Crypt Spider', mesh: 'models/creatures/spider.glb',
    clips: 'native', hide: /icosphere/i, height: 1.15, radius: 0.48, speed: 3.8, hp: 48,
    kind: 'grunt', role: 'warrior', brain: 'pursue', biome: 'grim',
    biomes: ['grim', 'ancient', 'verdant', 'frost'],
    attacks: ['swipe', 'slash'], telegraph: 'cone',
  },
  frog: {
    id: 'frog', label: 'Cave Frog', mesh: 'models/creatures/frog.glb',
    clips: 'native', hide: /icosphere/i, height: 1.05, radius: 0.4, speed: 2.8, hp: 40,
    kind: 'grunt', role: 'warrior', brain: 'pursue', biome: 'verdant',
    biomes: ['verdant', 'grim'],
    attacks: ['swipe', 'circle'], telegraph: 'cone',
  },
  fat_brute: {
    id: 'fat_brute', label: 'Fat Brute', mesh: 'models/creatures/fat_brute.glb',
    clips: 'native', hide: /icosphere/i, height: 2.05, radius: 0.72, speed: 2.2, hp: 170,
    kind: 'elite', role: 'warrior', brain: 'pursue', biome: 'grim',
    biomes: ['grim', 'molten'],
    attacks: ['slash', 'column', 'circle'], telegraph: 'aoe',
  },
  goblin_shaman: {
    id: 'goblin_shaman', label: 'Goblin Shaman', mesh: 'models/creatures/goblin_shaman.glb',
    clips: 'native', hide: null, height: 1.55, radius: 0.38, speed: 2.6, hp: 55,
    kind: 'caster', role: 'mage', brain: 'kite', biome: 'verdant',
    biomes: ['verdant', 'grim', 'ancient'],
    attacks: ['fire_fan', 'linear', 'circle'], telegraph: 'incoming',
  },
  ice_elemental: {
    id: 'ice_elemental', label: 'Ice Elemental', mesh: 'models/creatures/ice_elemental.glb',
    clips: 'native', hide: /icosphere/i, height: 2.4, radius: 0.75, speed: 1.9, hp: 200,
    kind: 'elite', role: 'mage', brain: 'kite', biome: 'frost',
    biomes: ['frost', 'ancient'],
    attacks: ['linear', 'circle', 'column'], telegraph: 'incoming',
  },
  lava_elemental: {
    id: 'lava_elemental', label: 'Lava Elemental', mesh: 'models/creatures/lava_elemental.glb',
    clips: 'native', hide: /icosphere/i, height: 2.45, radius: 0.78, speed: 2.0, hp: 210,
    kind: 'elite', role: 'mage', brain: 'pursue', biome: 'molten',
    biomes: ['molten', 'grim'],
    attacks: ['fire_fan', 'earth_spike', 'circle'], telegraph: 'aoe',
  },
  ogre: {
    id: 'ogre', label: 'Ogre', mesh: 'models/creatures/ogre.glb',
    clips: 'native', hide: /icosphere|axe|club/i, keep: /ogre_01|Object_7|sword/i,
    height: 2.5, radius: 0.8, speed: 2.1, hp: 230,
    kind: 'miniboss', role: 'warrior', brain: 'pursue', biome: 'grim',
    biomes: ['grim', 'verdant', 'molten'],
    attacks: ['slash', 'earth_spike', 'column'], telegraph: 'cone',
  },
};

export function creatureOf(id) {
  return CREATURES[id] || null;
}

export function creaturesForBiome(biomeId) {
  return Object.values(CREATURES).filter((c) => (c.biomes || [c.biome]).includes(biomeId));
}
